version: '3'

services:
  backend:
    build:
      context: ./django
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./react/blogapi
    volumes:
      - react_build:/react/build

  nginx:
    image: nginx:latest
    # restart: always
    ports:
      - 80:8080
    #  - 443:443
    volumes:
      - ./conf.d:/etc/nginx/conf.d/:ro
      - react_build:/var/www/react
    #  - /opt/nginx-ssl/dhparam:/etc/nginx/dhparam
    #  - /opt/nginx-ssl/certbot/conf/:/etc/nginx/ssl/
    #  - /opt/nginx-ssl/certbot/data:/usr/share/nginx/html/letsencrypt
    depends_on:
      - backend
      - frontend
  # certbot:
  #    image: certbot/certbot:latest
  #    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email hd.stein@web.de --agree-tos -->
  #    volumes:
  #      - /opt/nginx-ssl/certbot/conf/:/etc/letsencrypt
  #      - /opt/nginx-ssl/certbot/logs/:/var/log/letsencrypt
  #      - /opt/nginx-ssl/certbot/data:/usr/share/nginx/html/letsencrypt

volumes:
  react_build: